### ISSUE TITLE
The entity culling whitelist is not working on version 1.5.0 and above

### ISSUE THREAD

**Issue by xelotex** [SrRapero720/chloride#103]
Ice and fire is in the whitelist, but ice and fire entities still get affected regardless.

**Comment by SrRapero720** [comment]
ok i will look into it

**Comment by SrRapero720** [comment]
Did you use the new wildcard config? it got changed from `modid:*` to `modid:all`,
chloride by default converts old to new, but is quite strange

**Comment by xelotex** [comment]
Sorry, it didn't notify me about your reply. But yes i'm using the new config, i even made sure to delete the old one and the culling still affects ice and fire mobs, even ghasts.

![Image](https://github.com/user-attachments/assets/77d2920c-2df6-427e-9859-339208f314c6)

**Comment by SrRapero720** [comment]
OMG I am an idiot.
![Image](https://github.com/user-attachments/assets/d0e03667-d3d0-4061-8ded-2d743edb609f)

fix is coming soon

**Comment by SrRapero720** [comment]
fixed

**Comment by xelotex** [comment]
Seems like this issue still persists. Its working for the ghast but not for the ice and fire mobs. I'm using version 1.7.2 of the mod.
