### ISSUE TITLE
Missing MixinExtra dependency on 1.19 and below 

### ISSUE THREAD

**Issue by wsxiya** [SrRapero720/chloride#58]
embeddiumplus-1.19.2-v1.2.10 is incompatible with Embeddium-1.19.2-0.3.18 and crashes on game launch

**Comment by wsxiya** [comment]
This should also be true in 1.18.2

**Comment by SrRapero720** [comment]
???
Is compatible, I tested it
Please send me the crash report

**Comment by wsxiya** [comment]
![GBAA`~0)ZRFZH189EOA`I6F](https://github.com/SrRapero720/EmbeddiumPlus/assets/114494454/be2e1912-2ce6-4fc4-9e4a-8df558c631ed)
[错误报告-2024.5.13_23.34.03.zip](https://github.com/SrRapero720/EmbeddiumPlus/files/15296819/-2024.5.13_23.34.03.zip)

**Comment by SrRapero720** [comment]
Try installing modern fix as a temporary workaround 
I know what is happening

**Comment by wsxiya** [comment]
> 尝试安装现代修复程序作为临时解决方法，我知道发生了什么

Install modernfix to start the game, thank you

**Comment by SrRapero720** [comment]
fixed, download the update from CurseForge or MR

**Comment by wsxiya** [comment]
> 修复，从 CurseForge 或 MR 下载更新

The game still crashes when starting version 1.2.11
[Uploading 错误报告-2024.5.14_12.24.12.zip…]()
